"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {GAME_SECONDS,SCORE_CONFIG,STORAGE_KEYS,TEACHER_PASSWORD} from "./config";
import {questions,Question} from "./questions";

type Screen="home"|"map"|"stage"|"summary"|"result";
type Stage={id:string;no:string;title:string;short:string;icon:string;minutes:number;chapter:string;color:string};
type Saved={name:string;className:string;score:number;combo:number;maxCombo:number;correct:number;wrong:number;stage:number;task:number;seconds:number;scores:number[];screen:Screen;startedAt:number};
type Board={name:string;className:string;score:number;seconds:number;accuracy:number;date:string};
const stages:Stage[]=[
 {id:"science",no:"01",title:"科學家的實驗室",short:"科學探究",icon:"⌁",minutes:4,chapter:"1-1",color:"#38e8ca"},
 {id:"life",no:"02",title:"生命現象快問快答",short:"生命現象",icon:"⚡",minutes:3,chapter:"1-2",color:"#6be7ff"},
 {id:"microscope",no:"03",title:"顯微鏡操作室",short:"顯微鏡",icon:"⌕",minutes:5,chapter:"1-2",color:"#a5ff69"},
 {id:"cell",no:"04",title:"打造一顆細胞",short:"細胞構造",icon:"◉",minutes:5,chapter:"1-3 / 1-5",color:"#c99cff"},
 {id:"osmosis",no:"05",title:"細胞生存危機",short:"物質進出",icon:"◌",minutes:4,chapter:"1-4",color:"#62caff"},
 {id:"nutrition",no:"06",title:"人體營養研究所",short:"食物養分",icon:"⌬",minutes:5,chapter:"2-1",color:"#ffcb68"},
 {id:"enzyme",no:"07",title:"酵素實驗室",short:"酵素",icon:"◇",minutes:5,chapter:"2-2",color:"#ff879e"},
 {id:"boss",no:"08",title:"BIO ESCAPE",short:"FINAL BOSS",icon:"✦",minutes:5,chapter:"綜合挑戰",color:"#b9ff58"}
];
const scienceOrder=["觀察","提出問題","提出假說","設計並進行實驗","分析實驗結果","提出結論"];
const shuffle=<T,>(a:T[])=>[...a].sort(()=>Math.random()-.5);
export function calculateScore(correct:boolean,elapsed:number,combo:number){if(!correct)return 0;const speed=Math.max(0,Math.round(SCORE_CONFIG.maxSpeed*(1-elapsed/20)));return SCORE_CONFIG.correct+speed+(SCORE_CONFIG.combo[combo]||0)}
const fresh=(name="",className=""):Saved=>({name,className,score:0,combo:0,maxCombo:0,correct:0,wrong:0,stage:0,task:0,seconds:GAME_SECONDS,scores:Array(8).fill(0),screen:"map",startedAt:Date.now()});

function Choice({q,onAnswer}:{q:Question,onAnswer:(ok:boolean)=>void}){const[value,setValue]=useState("");const[feedback,setFeedback]=useState<null|boolean>(null);const answer=(v:string)=>{if(feedback!==null)return;setValue(v);const ok=v.trim().toLowerCase()===q.answer.toLowerCase();setFeedback(ok);setTimeout(()=>onAnswer(ok),1200)};return <div className="question-card"><span className="task-type">DATA ANALYSIS</span><h2>{q.question}</h2>{q.type==="input"?<div className="input-answer"><input inputMode="numeric" value={value} onChange={e=>setValue(e.target.value)} placeholder="輸入答案"/><button onClick={()=>answer(value)}>確認</button></div>:<div className="answer-grid">{q.options?.map((o,i)=><button key={o} onClick={()=>answer(o)} className={value===o?(feedback?"right":"wrong"):""}><i>{String.fromCharCode(65+i)}</i>{o}</button>)}</div>}{feedback!==null&&<div className={`feedback ${feedback?"ok":"no"}`}><b>{feedback?"正確！ + SCORE":"再想一下"}</b><span>{q.explanation}</span></div>}</div>}

function SortTask({onDone,plant=false}:{onDone:(ok:boolean)=>void;plant?:boolean}){const target=plant?["細胞","組織","器官","個體"]:scienceOrder;const[items,setItems]=useState(()=>shuffle(target));const move=(i:number,d:number)=>{const n=[...items],j=i+d;if(j<0||j>=n.length)return;[n[i],n[j]]=[n[j],n[i]];setItems(n)};const check=()=>onDone(items.every((x,i)=>x===target[i]));return <div className="question-card"><span className="task-type">SEQUENCE PROTOCOL</span><h2>{plant?"排列植物體的組成層次":"重建科學方法流程"}</h2><p className="hint">使用箭頭調整卡片順序，再送出驗證。</p><div className="sort-list">{items.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><button onClick={()=>move(i,-1)} aria-label="上移">↑</button><button onClick={()=>move(i,1)} aria-label="下移">↓</button></div>)}</div><button className="action" onClick={check}>驗證流程</button></div>}

function Classify({onDone}:{onDone:(ok:boolean)=>void}){const cards=["每天照光時間","綠豆苗最後高度","每天澆水量","植物種類","土壤種類","種植天數"];const[placed,setPlaced]=useState<Record<string,string>>({});const expected:Record<string,string>={"每天照光時間":"操作變因","綠豆苗最後高度":"應變變因","每天澆水量":"控制變因","植物種類":"控制變因","土壤種類":"控制變因","種植天數":"控制變因"};return <div className="question-card"><span className="task-type">VARIABLE SCAN</span><h2>照光時間會影響綠豆苗高度嗎？</h2><p className="hint">先點資料卡，再選擇它的變因類型。</p><div className="classify-list">{cards.map(c=><div key={c}><span>{c}</span><select value={placed[c]||""} onChange={e=>setPlaced(p=>({...p,[c]:e.target.value}))}><option value="">選擇分類</option><option>操作變因</option><option>控制變因</option><option>應變變因</option></select></div>)}</div><button className="action" disabled={Object.keys(placed).length<6} onClick={()=>onDone(cards.every(c=>placed[c]===expected[c]))}>送出分類</button></div>}

function Microscope({onDone}:{onDone:(ok:boolean)=>void}){const[high,setHigh]=useState(false);const[pos,setPos]=useState({x:62,y:66});const dragging=useRef(false);const pointer=(e:React.PointerEvent)=>{if(!dragging.current)return;const r=e.currentTarget.getBoundingClientRect();setPos({x:Math.max(12,Math.min(88,(e.clientX-r.left)/r.width*100)),y:Math.max(12,Math.min(88,(e.clientY-r.top)/r.height*100))})};return <div className="question-card microscope-task"><span className="task-type">LIVE OPTICS</span><h2>把右下方細胞移到視野中央</h2><p className="hint">拖曳玻片；複式顯微鏡的影像移動方向與玻片相反。</p><div className={`scope ${high?"high":""}`} onPointerMove={pointer} onPointerUp={()=>dragging.current=false} onPointerLeave={()=>dragging.current=false}><div className="cell-dot" style={{left:`${100-pos.x}%`,top:`${100-pos.y}%`}}/><div className="crosshair">＋</div><button className="slide" style={{transform:`translate(${pos.x-50}px,${pos.y-50}px)`}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);dragging.current=true}}>玻片</button></div><div className="scope-actions"><button onClick={()=>setHigh(x=>!x)}>{high?"切回低倍鏡":"切換高倍鏡"}</button><button className="action" onClick={()=>onDone(Math.abs(pos.x-50)<10&&Math.abs(pos.y-50)<10)}>確認置中</button></div></div>}

function CellBuild({onDone}:{onDone:(ok:boolean)=>void}){const parts=["細胞壁","細胞膜","細胞質","細胞核","大液泡","葉綠體","粒線體"];const[added,setAdded]=useState<string[]>([]);return <div className="question-card"><span className="task-type">CELL ASSEMBLY</span><h2>打造一顆植物細胞</h2><p className="hint">依序點擊構造，組裝完整植物細胞。</p><div className="cell-builder"><div className="plant-cell">{added.includes("細胞核")&&<i className="nucleus"/>}{added.includes("大液泡")&&<i className="vacuole"/>}{added.includes("葉綠體")&&[1,2,3].map(i=><i className={`chloro c${i}`} key={i}/>)}<span>{added.length}/7</span></div><div className="part-bank">{parts.map(p=><button className={added.includes(p)?"used":""} onClick={()=>setAdded(a=>a.includes(p)?a:[...a,p])} key={p}>{p}</button>)}</div></div><button className="action" onClick={()=>onDone(added.length===parts.length)}>完成組裝</button></div>}

function Osmosis({onDone}:{onDone:(ok:boolean)=>void}){const[solution,setSolution]=useState("");const[predict,setPredict]=useState("");const expected:Record<string,string>={"清水":"膨脹","等濃度":"維持原狀","濃食鹽水":"萎縮"};return <div className="question-card"><span className="task-type">OSMOSIS SIMULATOR</span><h2>紅血球進入溶液後會怎樣？</h2><div className="bottles">{Object.keys(expected).map(x=><button className={solution===x?"active":""} onClick={()=>setSolution(x)} key={x}><i/><b>{x}</b></button>)}</div><p className="hint">選一瓶溶液，再預測細胞變化。</p><div className="prediction">{["膨脹","維持原狀","萎縮"].map(x=><button className={predict===x?"active":""} onClick={()=>setPredict(x)} key={x}>{x}</button>)}</div><button className="action" disabled={!solution||!predict} onClick={()=>onDone(expected[solution]===predict)}>播放模擬</button></div>}

function Nutrition({onDone}:{onDone:(ok:boolean)=>void}){const nutrients=["醣類","蛋白質","脂質","維生素","礦物質","水"];const[energy,setEnergy]=useState<string[]>([]);return <div className="question-card"><span className="task-type">NUTRIENT SCAN</span><h2>哪些養分可以提供能量？</h2><p className="hint">點選所有能供能的養分。</p><div className="nutrients">{nutrients.map(n=><button className={energy.includes(n)?"active":""} onClick={()=>setEnergy(a=>a.includes(n)?a.filter(x=>x!==n):[...a,n])} key={n}>{n}</button>)}</div><div className="calorie-bars"><i style={{height:44}}><b>4</b><span>醣類</span></i><i style={{height:44}}><b>4</b><span>蛋白質</span></i><i style={{height:90}}><b>9</b><span>脂質</span></i></div><button className="action" onClick={()=>onDone(energy.length===3&&["醣類","蛋白質","脂質"].every(x=>energy.includes(x)))}>分析結果</button></div>}

function Enzyme({onDone}:{onDone:(ok:boolean)=>void}){const[temp,setTemp]=useState(37);const activity=temp<40?Math.round(temp/40*100):Math.max(0,100-(temp-40)*2.5);return <div className="question-card"><span className="task-type">ENZYME ACTIVITY</span><h2>溫度如何影響酵素活性？</h2><div className="enzyme-meter"><div className="curve"><i style={{height:`${activity}%`}}/><b>{Math.round(activity)}%</b><span>相對活性</span></div><div><output>{temp}°C</output><input type="range" min="0" max="80" value={temp} onChange={e=>setTemp(+e.target.value)}/><p>{temp<20?"低溫：反應較慢":temp<=45?"接近最適範圍：活性較高":"溫度過高：活性快速下降"}</p></div></div><button className="action" onClick={()=>onDone(temp>=35&&temp<=45)}>將溫度調到活性較高的範圍並確認</button></div>}

function StageTask({stage,task,onDone}:{stage:Stage;task:number;onDone:(ok:boolean)=>void}){const qs=questions.filter(q=>q.stage===stage.id);const bossPool=questions.filter(q=>["science","microscope","cell","osmosis","nutrition","enzyme","boss"].includes(q.stage));const picked=useMemo(()=>{const pool=stage.id==="boss"?bossPool:qs;return pool[Math.floor(Math.random()*pool.length)]},[stage.id,task]);if(stage.id==="science")return task===0?<SortTask onDone={onDone}/>:task===1?<Classify onDone={onDone}/>:<Choice q={picked} onAnswer={onDone}/>;if(stage.id==="microscope")return task===0?<Microscope onDone={onDone}/>:<Choice q={picked} onAnswer={onDone}/>;if(stage.id==="cell")return task===0?<CellBuild onDone={onDone}/>:task===1?<SortTask plant onDone={onDone}/>:<Choice q={picked} onAnswer={onDone}/>;if(stage.id==="osmosis")return task===0?<Osmosis onDone={onDone}/>:<Choice q={picked} onAnswer={onDone}/>;if(stage.id==="nutrition")return task===0?<Nutrition onDone={onDone}/>:<Choice q={picked} onAnswer={onDone}/>;if(stage.id==="enzyme")return task===0?<Enzyme onDone={onDone}/>:<Choice q={picked} onAnswer={onDone}/>;return <Choice q={picked} onAnswer={onDone}/>}

export default function App(){
 const[name,setName]=useState("");const[className,setClassName]=useState("");const[game,setGame]=useState<Saved|null>(null);const[screen,setScreen]=useState<Screen>("home");const[taskStart,setTaskStart]=useState(Date.now());const[toast,setToast]=useState("");const[sound,setSound]=useState(true);const[teacher,setTeacher]=useState(false);const[password,setPassword]=useState("");const[board,setBoard]=useState<Board[]>([]);
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEYS.game);if(saved){const g=JSON.parse(saved);setName(g.name);setClassName(g.className);setGame(g)}setBoard(JSON.parse(localStorage.getItem(STORAGE_KEYS.board)||"[]"))}catch{}},[]);
 useEffect(()=>{if(!game)return;localStorage.setItem(STORAGE_KEYS.game,JSON.stringify({...game,screen}));},[game,screen]);
 useEffect(()=>{if(!game||!["map","stage"].includes(screen))return;const t=setInterval(()=>setGame(g=>g?{...g,seconds:Math.max(0,g.seconds-1)}:g),1000);return()=>clearInterval(t)},[screen,!!game]);
 const beep=(ok:boolean)=>{if(!sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=ok?660:220;g.gain.value=.035;o.start();o.stop(c.currentTime+.12)}catch{}};
 const start=()=>{const g=fresh(name.trim(),className.trim());setGame(g);setScreen("map")};
 const resume=()=>{if(game)setScreen(game.screen==="home"?"map":game.screen)};
 const tasksFor=(id:string)=>id==="boss"?10:id==="life"?8:["microscope","cell","nutrition","enzyme"].includes(id)?4:3;
 const answer=(ok:boolean)=>{if(!game)return;beep(ok);const newCombo=ok?game.combo+1:0;const gained=calculateScore(ok,(Date.now()-taskStart)/1000,newCombo);const scores=[...game.scores];scores[game.stage]+=gained;const next={...game,score:game.score+gained,combo:newCombo,maxCombo:Math.max(game.maxCombo,newCombo),correct:game.correct+(ok?1:0),wrong:game.wrong+(ok?0:1),scores};setToast(ok?`正確！ +${gained}`:"位置不對，再試一次");setTimeout(()=>setToast(""),900);const count=tasksFor(stages[game.stage].id);if(game.task+1>=count){setGame({...next,task:0});setScreen("summary")}else{setGame({...next,task:game.task+1});setTaskStart(Date.now())}};
 const nextStage=()=>{if(!game)return;if(game.stage===7){finish()}else{setGame({...game,stage:game.stage+1,task:0});setScreen("map")}};
 const finish=()=>{if(!game)return;const elapsed=GAME_SECONDS-game.seconds,accuracy=Math.round(game.correct/Math.max(1,game.correct+game.wrong)*100);const rec={name:game.name,className:game.className,score:game.score,seconds:elapsed,accuracy,date:new Date().toLocaleDateString("zh-TW")};const list=[...board,rec].sort((a,b)=>b.score-a.score||a.seconds-b.seconds).slice(0,20);setBoard(list);localStorage.setItem(STORAGE_KEYS.board,JSON.stringify(list));setScreen("result")};
 const reset=()=>{localStorage.removeItem(STORAGE_KEYS.game);setGame(null);setScreen("home");setTeacher(false)};
 const fmt=(s:number)=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;
 const accuracy=game?Math.round(game.correct/Math.max(1,game.correct+game.wrong)*100):0;const title=accuracy>=90?"生物研究首席特務":accuracy>=80?"高階生物調查員":accuracy>=70?"生物研究員":accuracy>=60?"實驗室見習生":"生物訓練生";
 return <main className="mission-shell">
  {screen==="home"&&<><header className="landing-nav"><Brand/><button className="teacher-link" onClick={()=>setTeacher(true)}>教師模式</button></header><section className="landing-grid"><div className="hero-copy"><div className="status-tag"><i/> RESEARCH CENTER ONLINE</div><p className="eyebrow">國一生物・個人闖關賽</p><h1>生物特務<br/><em>挑戰</em></h1><p className="hero-lead">進入研究中心，完成 8 項生物任務。<br/>觀察、推理、操作——證明你的研究實力。</p><div className="mission-stats"><div><b>08</b><span>MISSION</span></div><div><b>35</b><span>MINUTES</span></div><div><b>∞</b><span>DISCOVERY</span></div></div></div><div className="access-card"><div className="card-head"><span>AGENT ACCESS</span><i>01</i></div><h2>特務報到</h2><p>輸入資料，啟動你的生物研究任務。</p><label>學生姓名<input value={name} onChange={e=>setName(e.target.value)} placeholder="請輸入姓名"/></label><label>班級<input value={className} onChange={e=>setClassName(e.target.value)} placeholder="例如：701"/></label><button className="start-button" disabled={!name.trim()||!className.trim()} onClick={start}>開始任務 <span>→</span></button>{game&&<button className="resume" onClick={resume}>繼續上次任務・{game.score} 分</button>}<small className="save-note">進度將自動儲存在這台裝置</small></div></section></>}
  {game&&screen!=="home"&&screen!=="result"&&<><GameHeader game={game} sound={sound} setSound={setSound} fmt={fmt}/>{screen==="map"&&<section className="map-page"><div className="map-title"><p>MISSION CONTROL / {game.name}・{game.className}</p><h1>任務路線圖</h1><span>完成全部研究任務，解鎖核心研究中心。</span></div><div className="stage-map">{stages.map((s,i)=><button key={s.id} disabled={i>game.stage} className={`${i<game.stage?"done":""} ${i===game.stage?"current":""}`} style={{"--stage":s.color} as React.CSSProperties} onClick={()=>{if(i===game.stage){setTaskStart(Date.now());setScreen("stage")}}}><div className="stage-icon">{i<game.stage?"✓":s.icon}</div><span>MISSION {s.no}</span><b>{s.title}</b><small>{s.chapter}・約 {s.minutes} 分鐘</small>{i===game.stage&&<em>開始任務 →</em>}</button>)}</div></section>}{screen==="stage"&&<section className="stage-page"><div className="stage-meta" style={{"--stage":stages[game.stage].color} as React.CSSProperties}><span>MISSION {stages[game.stage].no}</span><h1>{stages[game.stage].title}</h1><div><b>{game.task+1}</b> / {tasksFor(stages[game.stage].id)}</div></div><div className="task-progress"><i style={{width:`${(game.task+1)/tasksFor(stages[game.stage].id)*100}%`}}/></div><StageTask key={`${game.stage}-${game.task}`} stage={stages[game.stage]} task={game.task} onDone={answer}/></section>}{screen==="summary"&&<section className="summary-page"><div className="summary-badge">MISSION {stages[game.stage].no} COMPLETE</div><h1>任務完成</h1><p>{stages[game.stage].title}</p><div className="summary-score"><span>本關得分</span><b>{game.scores[game.stage].toLocaleString()}</b></div><div className="summary-grid"><div><span>正確率</span><b>{accuracy}%</b></div><div><span>目前總分</span><b>{game.score.toLocaleString()}</b></div><div><span>最大 Combo</span><b>×{game.maxCombo}</b></div></div><button className="action" onClick={nextStage}>{game.stage===7?"查看任務結算":"前往下一關 →"}</button></section>}</>}
  {game&&screen==="result"&&<section className="result-page"><div className="result-glow"/><span className="result-label">ALL MISSIONS COMPLETE</span><h1>任務完成！</h1><p className="rank-title">{title}</p><div className="agent-result"><span>{game.name}・{game.className}</span><b>{game.score.toLocaleString()}</b><small>TOTAL SCORE</small></div><div className="result-stats"><div><span>答對</span><b>{game.correct}</b></div><div><span>答錯</span><b>{game.wrong}</b></div><div><span>正確率</span><b>{accuracy}%</b></div><div><span>最大 Combo</span><b>×{game.maxCombo}</b></div><div><span>完成時間</span><b>{fmt(GAME_SECONDS-game.seconds)}</b></div></div><div className="score-breakdown">{stages.map((s,i)=><div key={s.id}><span>{s.short}</span><i><em style={{width:`${Math.min(100,game.scores[i]/15)}%`,background:s.color}}/></i><b>{game.scores[i]}</b></div>)}</div><Leaderboard board={board} fmt={fmt}/><button className="action" onClick={reset}>返回研究中心</button></section>}
  {teacher&&<div className="modal-back"><div className="teacher-modal"><button className="close" onClick={()=>setTeacher(false)}>×</button>{password!==TEACHER_PASSWORD?<><span className="task-type">TEACHER ACCESS</span><h2>教師模式</h2><p>請輸入教師密碼。</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="密碼"/><button className="action" onClick={()=>setPassword(password)}>登入</button>{password&&password!==TEACHER_PASSWORD&&<small className="error">密碼不正確</small>}</>:<><span className="task-type">CONTROL PANEL</span><h2>教師模式</h2><div className="teacher-stats"><div><b>{questions.length}</b><span>目前題庫</span></div><div><b>{new Set(questions.map(q=>q.chapter)).size}</b><span>涵蓋章節</span></div><div><b>{board.length}</b><span>本機紀錄</span></div></div><div className="answer-key">{questions.map(q=><details key={q.id}><summary>{q.id}・{q.question}</summary><p><b>答案：{q.answer}</b><br/>{q.explanation}</p></details>)}</div><Leaderboard board={board} fmt={fmt}/><div className="teacher-actions"><button onClick={()=>{setBoard([]);localStorage.removeItem(STORAGE_KEYS.board)}}>清除排行榜</button><button onClick={reset}>重設遊戲</button></div></>}</div></div>}
  {toast&&<div className="toast">{toast}</div>}<div className="lab-grid" aria-hidden="true"/>
 </main>
}
function Brand(){return <div className="brand-lockup"><span className="brand-atom">B</span><div><b>BIO MISSION</b><small>JUNIOR RESEARCH DIVISION</small></div></div>}
function GameHeader({game,sound,setSound,fmt}:{game:Saved;sound:boolean;setSound:(x:boolean)=>void;fmt:(n:number)=>string}){return <header className="game-header"><Brand/><div className="hud"><div><span>SCORE</span><b>{game.score.toLocaleString()}</b></div><div><span>COMBO</span><b>×{game.combo}</b></div><div className={game.seconds<300?"urgent":""}><span>TIME</span><b>{fmt(game.seconds)}</b></div><button onClick={()=>setSound(!sound)} aria-label="切換音效">{sound?"♪":"♩"}</button></div></header>}
function Leaderboard({board,fmt}:{board:Board[];fmt:(n:number)=>string}){return <div className="leaderboard"><h2>本機排行榜</h2><div className="board-head"><span>排名</span><span>特務</span><span>分數</span><span>時間</span><span>正確率</span></div>{board.length?board.slice(0,10).map((r,i)=><div className="board-row" key={`${r.name}-${r.date}-${i}`}><b>{i+1}</b><span>{r.name}<small>{r.className}</small></span><strong>{r.score}</strong><span>{fmt(r.seconds)}</span><span>{r.accuracy}%</span></div>):<p className="empty">尚無任務紀錄</p>}</div>}
