export type Question={id:string;chapter:string;stage:string;type:"choice"|"input";question:string;options?:string[];answer:string;explanation:string;points:number;difficulty:number};
export const questions:Question[]=[
{id:"1-1-001",chapter:"1-1",stage:"science",type:"choice",question:"『感染人數減少，可能與孩童更常洗手有關。』屬於哪一步？",options:["觀察","提出假說","進行實驗","提出結論"],answer:"提出假說",explanation:"這是尚待實驗驗證的可能解釋，因此是提出假說。",points:100,difficulty:1},
{id:"1-2-001",chapter:"1-2",stage:"life",type:"choice",question:"人體吃下食物後進行消化與吸收。",options:["代謝","生長與發育","生殖","感應與運動"],answer:"代謝",explanation:"消化與吸收是生物體內物質與能量轉換的代謝活動。",points:100,difficulty:1},
{id:"1-2-002",chapter:"1-2",stage:"life",type:"choice",question:"種子萌芽後逐漸長成植物。",options:["代謝","生長與發育","生殖","感應與運動"],answer:"生長與發育",explanation:"體型增加並逐漸成熟，屬於生長與發育。",points:100,difficulty:1},
{id:"1-2-003",chapter:"1-2",stage:"life",type:"choice",question:"手碰到燙的東西立刻縮回。",options:["代謝","生長與發育","生殖","感應與運動"],answer:"感應與運動",explanation:"感受刺激並產生縮手反應。",points:100,difficulty:1},
{id:"1-2-004",chapter:"1-2",stage:"life",type:"choice",question:"仙人掌的針狀葉主要有什麼功能？",options:["增加光合作用","減少水分散失","儲存大量養分","捕捉昆蟲"],answer:"減少水分散失",explanation:"針狀葉面積小，可降低水分散失。",points:100,difficulty:1},
{id:"1-2-005",chapter:"1-2",stage:"microscope",type:"input",question:"目鏡 10×、物鏡 40×，總倍率是多少？",answer:"400",explanation:"總倍率＝目鏡倍率×物鏡倍率＝400 倍。",points:100,difficulty:1},
{id:"1-3-001",chapter:"1-3",stage:"cell",type:"choice",question:"控制物質進出細胞的是？",options:["細胞膜","細胞核","粒線體","細胞壁"],answer:"細胞膜",explanation:"細胞膜能選擇性控制物質進出。",points:100,difficulty:1},
{id:"1-3-002",chapter:"1-3",stage:"cell",type:"choice",question:"洋蔥鱗片表皮細胞是否一定具有葉綠體？",options:["是","否"],answer:"否",explanation:"並非所有植物細胞都有葉綠體，洋蔥鱗片表皮通常沒有。",points:100,difficulty:2},
{id:"1-4-001",chapter:"1-4",stage:"osmosis",type:"choice",question:"物質自然由高濃度移向低濃度，稱為？",options:["擴散","蒸散","呼吸","消化"],answer:"擴散",explanation:"擴散使粒子由高濃度往低濃度移動，最後趨向均勻。",points:100,difficulty:1},
{id:"2-1-001",chapter:"2-1",stage:"nutrition",type:"choice",question:"下列何種養分每公克提供的熱量最高？",options:["醣類","蛋白質","脂質","維生素"],answer:"脂質",explanation:"脂質每公克約提供 9 大卡，醣類與蛋白質約 4 大卡。",points:100,difficulty:1},
{id:"2-1-002",chapter:"2-1",stage:"nutrition",type:"input",question:"蛋白質5g、脂質10g、醣類20g，共多少 kcal？",answer:"190",explanation:"5×4＋10×9＋20×4＝190 kcal。",points:100,difficulty:2},
{id:"2-1-003",chapter:"2-1",stage:"nutrition",type:"choice",question:"碘液遇到澱粉會呈現什麼顏色？",options:["藍黑色","磚紅色","淡藍色","無色"],answer:"藍黑色",explanation:"碘液可檢測澱粉，陽性反應為藍黑色。",points:100,difficulty:1},
{id:"2-2-001",chapter:"2-2",stage:"enzyme",type:"choice",question:"酵素只能與特定受質作用，這種特性稱為？",options:["專一性","擴散性","恆定性","生殖性"],answer:"專一性",explanation:"酵素的作用部位只適合特定受質。",points:100,difficulty:1},
{id:"2-2-002",chapter:"2-2",stage:"enzyme",type:"choice",question:"溫度越高，酵素活性一定越高嗎？",options:["是","不是"],answer:"不是",explanation:"過高溫度可能破壞酵素構造，使活性下降。",points:100,difficulty:1},
{id:"1-5-001",chapter:"1-5",stage:"boss",type:"choice",question:"植物體的組成層次不包含哪一項？",options:["細胞","組織","器官系統","個體"],answer:"器官系統",explanation:"植物為細胞→組織→器官→個體，不列器官系統。",points:100,difficulty:2},
{id:"1-1-002",chapter:"1-1",stage:"science",type:"choice",question:"研究者主動改變的實驗因素稱為？",options:["操作變因","控制變因","應變變因","實驗結果"],answer:"操作變因",explanation:"操作變因是研究者為了探討影響而主動改變的因素。",points:100,difficulty:1},
{id:"1-1-003",chapter:"1-1",stage:"science",type:"choice",question:"若實驗結果不支持假說，最適當的處理是？",options:["修改數據","直接宣布假說正確","修正假說或調整實驗設計","停止所有研究"],answer:"修正假說或調整實驗設計",explanation:"科學探究會依證據修正假說，並檢查實驗設計是否合理。",points:100,difficulty:2},
{id:"1-1-004",chapter:"1-1",stage:"science",type:"choice",question:"設置實驗組與對照組時，除了研究變因外，其餘條件應如何？",options:["盡可能相同","全部不同","隨機改變","不必記錄"],answer:"盡可能相同",explanation:"控制其他條件一致，才能判斷結果是否由主要研究變因造成。",points:100,difficulty:1},
{id:"1-2-006",chapter:"1-2",stage:"life",type:"choice",question:"母貓生下小貓，屬於哪種生命現象？",options:["代謝","生長與發育","生殖","感應與運動"],answer:"生殖",explanation:"產生下一代屬於生殖現象。",points:100,difficulty:1},
{id:"1-2-007",chapter:"1-2",stage:"life",type:"choice",question:"植物莖朝光源方向生長，屬於哪種生命現象？",options:["代謝","生長與發育","生殖","感應與運動"],answer:"感應與運動",explanation:"植物感受光刺激並產生向光生長反應。",points:100,difficulty:1},
{id:"1-2-008",chapter:"1-2",stage:"life",type:"choice",question:"植物利用光製造養分，主要屬於哪種生命現象？",options:["代謝","生長與發育","生殖","感應與運動"],answer:"代謝",explanation:"製造養分涉及物質與能量轉換，屬於代謝。",points:100,difficulty:1},
{id:"1-2-009",chapter:"1-2",stage:"life",type:"choice",question:"蝙蝠在黑暗洞穴中辨認方向主要依靠？",options:["視力","回聲定位","光合作用","胎生苗"],answer:"回聲定位",explanation:"蝙蝠可發出聲波並接收回聲來判斷障礙物與獵物位置。",points:100,difficulty:1},
{id:"1-2-010",chapter:"1-2",stage:"microscope",type:"input",question:"目鏡 10×、物鏡 4×，總倍率是多少？",answer:"40",explanation:"總倍率＝10×4＝40 倍。",points:100,difficulty:1},
{id:"1-2-011",chapter:"1-2",stage:"microscope",type:"choice",question:"由低倍鏡換成高倍鏡後，視野中的細胞影像會如何？",options:["變大、數量變少","變小、數量變多","大小不變、變亮","變小、數量變少"],answer:"變大、數量變少",explanation:"高倍鏡視野較小、較暗，影像較大，看到的細胞數較少。",points:100,difficulty:1},
{id:"1-2-012",chapter:"1-2",stage:"microscope",type:"choice",question:"使用高倍物鏡觀察時，主要使用哪一個調節輪？",options:["粗調節輪","細調節輪","旋轉盤","光圈"],answer:"細調節輪",explanation:"高倍觀察主要以細調節輪微調，避免鏡頭壓破玻片。",points:100,difficulty:2},
{id:"1-2-013",chapter:"1-2",stage:"microscope",type:"choice",question:"複式顯微鏡下看到的影像通常是？",options:["正立實像","平面反像","只左右相反","只上下顛倒"],answer:"平面反像",explanation:"複式顯微鏡影像上下顛倒、左右相反。",points:100,difficulty:1},
{id:"1-3-003",chapter:"1-3",stage:"cell",type:"choice",question:"產生細胞活動所需能量的構造是？",options:["粒線體","液泡","細胞壁","細胞核"],answer:"粒線體",explanation:"粒線體能釋放養分中的能量，供細胞活動使用。",points:100,difficulty:1},
{id:"1-3-004",chapter:"1-3",stage:"cell",type:"choice",question:"內含遺傳物質 DNA 的主要構造是？",options:["細胞核","細胞膜","細胞質","液泡"],answer:"細胞核",explanation:"細胞核含遺傳物質，並與細胞生命活動的控制有關。",points:100,difficulty:1},
{id:"1-3-005",chapter:"1-3",stage:"cell",type:"choice",question:"植物細胞壁的主要成分是？",options:["纖維素","脂質","澱粉","葡萄糖"],answer:"纖維素",explanation:"植物細胞壁主要由纖維素構成，可保護並維持細胞形狀。",points:100,difficulty:2},
{id:"1-3-006",chapter:"1-3",stage:"cell",type:"choice",question:"下列哪一構造可進行光合作用？",options:["葉綠體","粒線體","細胞核","細胞膜"],answer:"葉綠體",explanation:"部分植物細胞的葉綠體可吸收光能並製造養分。",points:100,difficulty:1},
{id:"1-4-002",chapter:"1-4",stage:"osmosis",type:"choice",question:"紅血球放入清水後，最可能發生什麼變化？",options:["膨脹，嚴重時破裂","維持原狀","立即萎縮","長出細胞壁"],answer:"膨脹，嚴重時破裂",explanation:"清水中的水會進入紅血球；動物細胞沒有細胞壁，嚴重時可能破裂。",points:100,difficulty:1},
{id:"1-4-003",chapter:"1-4",stage:"osmosis",type:"choice",question:"植物細胞放入清水後通常不會破裂，主要原因是？",options:["有細胞壁支撐","沒有細胞膜","水無法進入","具有粒線體"],answer:"有細胞壁支撐",explanation:"細胞壁可提供支撐，限制植物細胞過度膨脹。",points:100,difficulty:1},
{id:"1-4-004",chapter:"1-4",stage:"osmosis",type:"choice",question:"下列何者分子太大，通常需先分解才能被細胞利用？",options:["氧氣","水","澱粉","二氧化碳"],answer:"澱粉",explanation:"澱粉是大型分子，需先分解成較小分子。",points:100,difficulty:1},
{id:"1-4-005",chapter:"1-4",stage:"osmosis",type:"choice",question:"水通過細胞膜的擴散作用稱為？",options:["滲透","蒸散","消化","生殖"],answer:"滲透",explanation:"滲透是水分子通過選擇性通透膜的擴散作用。",points:100,difficulty:1},
{id:"1-5-002",chapter:"1-5",stage:"boss",type:"choice",question:"一個細胞即可表現完整生命現象的生物稱為？",options:["單細胞生物","多細胞生物","器官","組織"],answer:"單細胞生物",explanation:"單細胞生物只由一個細胞組成，仍能完成各種生命活動。",points:100,difficulty:1},
{id:"1-5-003",chapter:"1-5",stage:"boss",type:"choice",question:"形態與功能相似的細胞集合形成？",options:["組織","器官","器官系統","個體"],answer:"組織",explanation:"相似細胞分工合作，形成具有特定功能的組織。",points:100,difficulty:1},
{id:"1-5-004",chapter:"1-5",stage:"boss",type:"choice",question:"下列何者是植物的生殖器官？",options:["根","莖","葉","花"],answer:"花",explanation:"花、果實和種子屬於植物的生殖器官。",points:100,difficulty:1},
{id:"2-1-004",chapter:"2-1",stage:"nutrition",type:"choice",question:"下列哪一組養分不能直接提供能量？",options:["維生素、礦物質、水","醣類、蛋白質、脂質","醣類、水、脂質","蛋白質、維生素、脂質"],answer:"維生素、礦物質、水",explanation:"維生素、礦物質和水不直接提供能量，但對生理作用很重要。",points:100,difficulty:1},
{id:"2-1-005",chapter:"2-1",stage:"nutrition",type:"choice",question:"本氏液隔水加熱主要用來檢測？",options:["葡萄糖","澱粉","蛋白質","脂質"],answer:"葡萄糖",explanation:"本氏液加熱後可檢測葡萄糖等還原糖，陽性顏色由綠至紅。",points:100,difficulty:1},
{id:"2-1-006",chapter:"2-1",stage:"nutrition",type:"input",question:"醣類 15g、蛋白質 10g、脂質 5g，共多少 kcal？",answer:"145",explanation:"15×4＋10×4＋5×9＝145 kcal。",points:100,difficulty:2},
{id:"2-1-007",chapter:"2-1",stage:"nutrition",type:"choice",question:"骨骼與牙齒的重要礦物質是？",options:["鈣質","纖維素","脂質","維生素C"],answer:"鈣質",explanation:"鈣質是骨骼與牙齒的重要組成成分。",points:100,difficulty:1},
{id:"2-2-003",chapter:"2-2",stage:"enzyme",type:"choice",question:"酵素在代謝反應中扮演什麼角色？",options:["催化劑","受質","產物","養分"],answer:"催化劑",explanation:"酵素可促進反應，反應後仍可重複使用。",points:100,difficulty:1},
{id:"2-2-004",chapter:"2-2",stage:"enzyme",type:"choice",question:"ABC → A＋B＋C 屬於哪一類代謝？",options:["分解作用","合成作用","滲透作用","擴散作用"],answer:"分解作用",explanation:"大分子變成小分子屬於分解作用。",points:100,difficulty:1},
{id:"2-2-005",chapter:"2-2",stage:"enzyme",type:"choice",question:"胃內酵素通常較適合哪種環境？",options:["酸性","中性","鹼性","任何環境都相同"],answer:"酸性",explanation:"胃內環境偏酸，胃內酵素通常在酸性環境作用較佳。",points:100,difficulty:1},
{id:"2-2-006",chapter:"2-2",stage:"enzyme",type:"choice",question:"小腸內酵素通常較適合哪種環境？",options:["鹼性","酸性","強酸性","完全無水"],answer:"鹼性",explanation:"小腸環境偏鹼，小腸內酵素通常在鹼性環境作用較佳。",points:100,difficulty:1},
{id:"2-2-007",chapter:"2-2",stage:"enzyme",type:"choice",question:"多數酵素的主要成分是？",options:["蛋白質","脂質","礦物質","水"],answer:"蛋白質",explanation:"國中課程中，多數酵素主要由蛋白質構成。",points:100,difficulty:1}
];
